variable "region" {}  
variable "Project_name" {}
variable "vpc_cidr" {}
variable "Public_subnet_azl_cidr" {}
variable "Public_subnet_az2_cidr" {}
variable "Private_app_subnet_az1_cidr" {}
variable "Private_app_subnet_az2_cidr" {}
variable "Private_data_subnet_az1_cidr" {}
variable "Private_data_subnet_az2_cidr" {}